json.extract! @spot,
  :location,
  :lng,
  :lat,
  :price,
  :description,
  :guest_limit,
  :bed_number,
  :bathroom_number,
  :property_type,
  :pets_allowed,
  :wireless_internet,
  :kitchen,
  :family_friendly,
  :monthly_discount
